apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels: 
    group: db
spec:
  type: ClusterIP
  selector:             
    app: postgres
  ports:
    - port: 5433
      name: postgres-accounts
      targetPort: 5433
    - port: 5431
      name: postgres-complaints
      targetPort: 5431
    - port: 5434
      name: postgres-news
      targetPort: 5434