apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: prometheusua/identity-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 8083
          env:
            - name: POSTGRESQL_FULLHOST
              value: postgres-identity
            - name: POSTGRESQL_DB
              value: accounts
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: db-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: db-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: jwt-secret-key
            - name: ACCESS_TOKEN_LIFE_millis
              value: '600000'
            - name: REFRESH_TOKEN_LIFE_millis
              value: '1800000'

---

apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31000
    - name: grpc
      port: 8083
      nodePort: 31003