apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-complaints
  labels:
    app: postgres-complaints
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-complaints
  template:
    metadata:
      labels:
        app: postgres-complaints
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: ""
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: complaints-secret
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: complaints-secret
                  key: db-password
            - name: POSTGRES_DB
              value: complaints
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-complaints
spec:
  selector:
    app: postgres-complaints
  ports:
    - protocol: TCP
      name: "5432"
      port: 5432
      targetPort: 5432
