apiVersion: v1
kind: Service
metadata:
  name: news-service
spec:
  selector:
    app: news-service
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 31002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
spec:
  selector:
    matchLabels:
      app: news-service
  replicas: 1
  template:
    metadata:
      labels:
        app: news-service
    spec:
      containers:
        - name: server
          image: prometheusua/news-service:latest
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: POSTGRESQL_FULLHOST
              value: postgres-news
            - name: POSTGRESQL_DB
              value: news
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: news-secret
                  key: db-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: news-secret
                  key: db-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: identity-secret
                  key: jwt-secret-key
            - name: AUTH_URL
              value: http://identity-service:8080